experimentName: FedDA-NNI-Tuning
trialCommand: python main_nni.py
trialCodeDirectory: .
trialConcurrency: 1 #导致一个显卡跑n个实验
trialGpuNumber: 1 #设置这个不能跑
maxTrialNumber: 100
searchSpaceFile: ./search_space/random_seed.json
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  maxTrialNumberPerGpu: 1
  useActiveGpu: True

#  useActiveGpu: false
#  gpuIndices: [0,3] #设置了要爆

