experimentName: strongDAsource3
trialCommand: python main.py
trialCodeDirectory: .
trialConcurrency: 1 #导致一个显卡跑n个实验
trialGpuNumber: 1 #设置这个不能跑
maxTrialNumber: 200
searchSpaceFile: ./search_space/strongDA.json
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  maxTrialNumberPerGpu: 1
  useActiveGpu: True

#  useActiveGpu: false
#  gpuIndices: [1,3] #设置了要爆

